/**
 *  BOARD_STATICS 스키마
 */

CREATE TABLE BOARD_STATICS(
            BOARDSTATID NUMBER PRIMARY KEY
           ,ACCOUNTID   VARCHAR2(50)
           ,BID         NUMBER
           ,VIEWED      VARCHAR2(1) CHECK(VIEWED IN('Y','N'))
           ,LATEST_VISITED_DATE DATE
           ,CONSTRAINT BAORD_STATICS_BID_FK FOREIGN KEY(BID) REFERENCES BOARD(BID)
);

SELECT * FROM BOARD_STATICS;
DROP TABLE BOARD_STATICS;