/**
 *  BOARD 스키마
 */

CREATE TABLE BOARD(
             BID        NUMBER PRIMARY KEY
            ,ACCOUNTID  VARCHAR2(50)
            ,BTITLE     VARCHAR2(300) NOT NULL
            ,BCONTENT   VARCHAR2(1000) NOT NULL
            ,CREATEDATE DATE DEFAULT(SYSDATE)
            ,VIEWCNT    NUMBER DEFAULT(0)
            ,CATEGORYID NUMBER
            ,PCONDITION NUMBER
            ,BUYSTATUS  VARCHAR2(50)
            ,CONSTRAINT BOARD_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)
            ,CONSTRAINT BOARD_CATEGORYID_FK FOREIGN KEY(CATEGORYID) REFERENCES CATEGORY(CATEGORYID)
);

CREATE SEQUENCE BOARD_SEQ NOCACHE;

SELECT * FROM BOARD;
DROP TABLE BOARD;