/**
 *  BOARD 스키마
 */

CREATE TABLE BOARD(
             BID        NUMBER PRIMARY KEY
            ,ACCOUNTID  VARCHAR2(50)
            ,BTITLE     VARCHAR2(300) NOT NULL
            ,BCONTENT   VARCHAR2(1000) NOT NULL
            ,CREATEDATE DATE DEFAULT(SYSDATE)
            ,VIEWCNT    NUMBER DEFAULT(0)
            ,CATEGORYID NUMBER
            ,PCONDITION VARCHAR2(20) CHECK(PCONDITION IN('중고', '새상품'))
            ,BUYSTATUS  VARCHAR2(50) NULL
            ,PRICE      NUMBER
            ,DEALMETHOD VARCHAR2(20) CHECK(DEALMETHOD IN('직거래', '택배거래'))
            ,CONSTRAINT BOARD_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)
            ,CONSTRAINT BOARD_CATEGORYID_FK FOREIGN KEY(CATEGORYID) REFERENCES CATEGORY(CATEGORYID)
);

CREATE SEQUENCE BOARD_SEQ NOCACHE;

SELECT * FROM BOARD;
DROP TABLE BOARD;

