/**
 *  ACCOUNTPHOTO 스키마
 */

--09.13 accountPhoto 회원프로필사진
CREATE TABLE ACCOUNTPHOTO(
             FILEID    NUMBER PRIMARY KEY
            ,ACCOUNTID VARCHAR2(50)
            ,UUIDNAME  VARCHAR2(50)  NOT NULL
            ,FILENAME  VARCHAR2(200) NOT NULL
            ,LOCATION  VARCHAR2(500) NOT NULL
            ,URL       VARCHAR2(500) NOT NULL 
            ,FILESIZE  NUMBER DEFAULT(0)
            ,FILETYPE  VARCHAR2(200) NOT NULL
            ,CONSTRAINT ACCOUNTPHOTO_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)
);

SELECT * FROM ACCOUNTPHOTO;
DROP TABLE ACCOUNTPHOTO;
