/**
 *  REVIEW 스키마
 */

CREATE TABLE REVIEW(
             ACCOUNTID VARCHAR2(50)
            ,BID NUMBER
            ,CONTENT   VARCHAR2(1000)
            ,STARSCORE NUMBER DEFAULT(0)
            ,DELETED   VARCHAR2(1) CHECK(DELETED IN('Y','N'))
            ,HIDDEN    VARCHAR2(1) CHECK(HIDDEN IN('Y','N'))
            ,CREATEDATE DATE DEFAULT(SYSDATE)
            ,CONSTRAINT REVIEW_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)
            ,CONSTRAINT REVIEW_BID_FK FOREIGN KEY(BID) REFERENCES BOARD(BID)
);

SELECT * FROM REVIEW;
DROP TABLE REVIEW;