/**
 *  REVIEW 스키마
 */

CREATE TABLE REVIEW(
             ACCOUNTID VARCHAR2(50)
            ,BID NUMBER
            ,CONTENT   VARCHAR2(1000)
            ,STARSCORE NUMBER DEFAULT(0)
            ,DELETED   VARCHAR2(1) CHECK(DELETED IN('Y','N'))
            ,HIDDEN    VARCHAR2(1) CHECK(HIDDEN IN('Y','N'))
            ,CREATEDATE DATE DEFAULT(SYSDATE)
            ,CONSTRAINT REVIEW_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID) ON DELETE CASCADE
            ,CONSTRAINT REVIEW_BID_FK FOREIGN KEY(BID) REFERENCES BOARD(BID)
);

SELECT * FROM REVIEW;
DROP TABLE REVIEW;


-- 테이블을 다시 만들지 않고 해당 제약조건만 수정하는 쿼리

-- 1. 아래 쿼리로 해당 제약조건을 삭제한 후
ALTER TABLE REVIEW DROP CONSTRAINT REVIEW_ACCOUNTID_FK;
-- 2. ON DELETE CASCADE를 적용시킨 제약조건을 다시 설정
ALTER TABLE REVIEW 
ADD CONSTRAINT REVIEW_ACCOUNTID_FK
FOREIGN KEY (ACCOUNTID) 
REFERENCES ACCOUNT (ACCOUNTID) 
ON DELETE CASCADE;
-- 3. 잘 설정되었는지 확인
SELECT *
  FROM USER_CONSTRAINTS
 WHERE TABLE_NAME = 'REVIEW';
