/**
 *  PRODUCT 스키마
 */

CREATE TABLE PRODUCT(
             PRODUCTID NUMBER PRIMARY KEY
            ,ACCOUNTID VARCHAR2(50)
            ,PRODUCTNAME VARCHAR2(200) NOT NULL
            ,CONSTRAINT PRODUCT_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)
); 

CREATE SEQUENCE PRODUCT_SEQ NOCACHE;

SELECT * FROM PRODUCT;
DROP TABLE PRODUCT;
