/**
 *  PROFILE_STATICS 스키마
 */

CREATE TABLE PROFILE_STATICS(
            PROFILEID NUMBER PRIMARY KEY
           ,ACCOUNTID VARCHAR2(50)
           ,VISITED   VARCHAR2(1) CHECK(VISITED IN('Y','N'))
           ,LATEST_VISITED_DATE DATE
           ,CONSTRAINT PROFILE_STATICS_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID) ON DELETE CASCADE
);

SELECT * FROM PROFILE_STATICS;
DROP TABLE PROFILE_STATICS;