/**
 *  CHAT 스키마
 */

CREATE TABLE CHAT(
             ACCOUNTID  VARCHAR2(50)
            ,READCHECK  VARCHAR2(1) CHECK(READCHECK IN('Y','N'))
            ,CONTENT    VARCHAR2(1000)
            ,CREATEDATE DATE DEFAULT(SYSDATE)
            ,FILENAME   VARCHAR2(200)
            ,FILESIZE   NUMBER
            ,FILETYPE   VARCHAR2(200)
            ,CONSTRAINT CHAT_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)
);

SELECT * FROM CHAT;
DROP TABLE CHAT;
