/**
 *  NOTICE 스키마
 */

CREATE  TABLE NOTICE(
              NOTICEID   NUMBER PRIMARY KEY
             ,ACCOUNTID  VARCHAR2(50)
             ,TITLE      VARCHAR2(300) NOT NULL
             ,CONTENT    VARCHAR2(1000) NOT NULL
             ,CREATEDATE DATE DEFAULT(SYSDATE)
             ,VIEWCNT    NUMBER
             ,CONSTRAINT NOTICE_ACCOUNTID_FK FOREIGN KEY(ACCOUNTID) REFERENCES ACCOUNT(ACCOUNTID)
);
CREATE SEQUENCE NOTICE_SEQ NOCACHE;

SELECT * FROM NOTICE;
DROP TABLE NOTICE;